import { Project } from '../types/Project';

export const mockProjects: Project[] = [
{
    vaultId: "36203",
    team: "Flagship Themes",
    theme: "KPI driven themes",
    project: "Horizon",
    mergedPhase: "build",
    doneDate: "2025-06-30",
    vaultStatus: "On Track",
    vaultPhase: "build",
    priority: "P0",
    champion: "Ben Sehl",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2024-12-30" },
    engineering: {
      effort: 84,
      plannedICs: 7,
      certainty: "Fuzzy aim",
      overflowWeeks: 0,
      minWeeks: 12,
      maxWeeks: 24,
      buildWeeks: "12w - 24w",
      endDate: "2025-06-16",
    },
    assignments: {
      "Q1C1-W2": 6,
      "Q1C1-W3": 7,
      "Q1C1-W4": 5,
    },
  },
  {
    vaultId: "44150",
    team: "Developer Tools",
    theme: "",
    project: "VS Code in Admin for Theme Editing",
    mergedPhase: "paused",
    doneDate: "2025-04-17",
    vaultStatus: "At Risk",
    vaultPhase: "paused",
    priority: "P0",
    champion: "CP Clermont",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-13" },
    engineering: {
      effort: 27,
      plannedICs: 3,
      certainty: "Fuzzy solution",
      overflowWeeks: 0,
      minWeeks: 9,
      maxWeeks: 14,
      buildWeeks: "9w - 14w",
      endDate: "2025-04-21",
    },
    assignments: {
      "Q1C1-W3": 1,
      "Q1C1-W4": 1,
      "Q1C1-W5": 2,
      "Q1C1-W6": 2,
      "Q1C2-W1": 1,
      "Q1C2-W2": 2,
      "Q1C2-W3": 3,
      "Q1C2-W4": 1,
      "Q1C2-W5": 2,
      "Q1C2-W6": 1,
      "Q2C1-W1": 3,
    },
  },
  {
    vaultId: "44150",
    team: "Developer Tools",
    theme: "",
    project: "Hot reloading in the theme editor (internal release)",
    mergedPhase: "paused",
    doneDate: "2025-03-20",
    vaultStatus: "At Risk",
    vaultPhase: "done",
    priority: "P1",
    champion: "Fran Dios",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-06" },
    engineering: {
      effort: 6,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 6,
      maxWeeks: 6,
      buildWeeks: "6w",
      endDate: "2025-02-17",
    },
    assignments: {},
  },
  {
    vaultId: "44150",
    team: "Developer Tools",
    theme: "",
    project: "LLM VS Code Extension from Hackdays",
    mergedPhase: "paused",
    doneDate: "2025-02-03",
    vaultStatus: "At Risk",
    vaultPhase: "paused",
    priority: "P1",
    champion: "Guilherme Carreiro",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-20" },
    engineering: {
      effort: 2,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 2,
      maxWeeks: 2,
      buildWeeks: "2w",
      endDate: "2025-02-03",
    },
    assignments: {
      "Q1C2-W1": 1,
      "Q1C2-W2": 1,
    },
  },
  {
    vaultId: "44152",
    team: "Developer Tools",
    theme: "",
    project: "Simplify common Liquid patterns",
    mergedPhase: "observe",
    doneDate: "2025-10-03",
    vaultStatus: "On Track",
    vaultPhase: "build",
    priority: "P0",
    champion: "Guilherme Carreiro",
    editions: "S'25",
    projectedStart: { cycle: "24-Q4C1", date: "2024-09-30" },
    engineering: {
      effort: 0,
      plannedICs: 0,
      certainty: "",
      overflowWeeks: 0,
      minWeeks: 0,
      maxWeeks: 0,
      buildWeeks: "",
      endDate: "",
    },
    assignments: {
      "Q1C1-W2": 1,
    },
  },
  {
    vaultId: "44310",
    team: "Developer Tools",
    theme: "",
    project: "Liquid inline boolean expressions",
    mergedPhase: "prototype",
    doneDate: "",
    vaultStatus: "On Track",
    vaultPhase: "paused",
    priority: "P0",
    champion: "James Meng",
    editions: "nan",
    projectedStart: { cycle: "25-Q1C2", date: "2025-03-04" },
    engineering: {
      effort: 21,
      plannedICs: 2,
      certainty: "Fuzzy solution",
      overflowWeeks: 0,
      minWeeks: 11,
      maxWeeks: 16,
      buildWeeks: "11w - 16w",
      endDate: "2025-06-24",
    },
    assignments: {
      "Q1C2-W3": 1,
      "Q1C2-W4": 2,
      "Q1C2-W5": 1,
    },
  },
  {
    vaultId: "44310",
    team: "Developer Tools",
    theme: "",
    project: "LiquidDoc",
    mergedPhase: "release",
    doneDate: "2025-05-05",
    vaultStatus: "On Track",
    vaultPhase: "release",
    priority: "P0",
    champion: "James Meng",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-06" },
    engineering: {
      effort: 10,
      plannedICs: 2,
      certainty: "Obvious solution",
      overflowWeeks: 12,
      minWeeks: 5,
      maxWeeks: 5,
      buildWeeks: "5w - 17w",
      endDate: "2025-05-05",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 2,
      "Q1C1-W5": 2,
      "Q1C1-W6": 3,
      "Q1C2-W1": 2,
      "Q1C2-W2": 2,
      "Q1C2-W3": 2,
      "Q1C2-W4": 3,
      "Q2C1-W1": 2,
      "Q2C1-W2": 3,
      "Q2C1-W3": 3,
      "Q2C1-W4": 3,
      "Q2C1-W5": 2,
      "Q2C1-W6": 1,
    },
  },
  {
    vaultId: "44152",
    team: "Developer Tools",
    theme: "",
    project: "Liquid array filters",
    mergedPhase: "nan",
    doneDate: "2025-02-10",
    vaultStatus: "At Risk",
    vaultPhase: "done",
    priority: "P0",
    champion: "Guilherme Carreiro",
    editions: "S'25",
    projectedStart: { cycle: "24-Q4C2", date: "2024-11-25" },
    engineering: {
      effort: 9,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 9,
      maxWeeks: 9,
      buildWeeks: "9w",
      endDate: "2025-01-27",
    },
    assignments: {
      "Q1C1-W2": 1,
    },
  },
  {
    vaultId: "44152",
    team: "Developer Tools",
    theme: "",
    project: "Liquid platform wishlist (Liquid context)",
    mergedPhase: "observe",
    doneDate: "2025-04-07",
    vaultStatus: "On Track",
    vaultPhase: "release",
    priority: "P0",
    champion: "Guilherme Carreiro",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-02-03" },
    engineering: {
      effort: 4,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 2,
      minWeeks: 4,
      maxWeeks: 4,
      buildWeeks: "4w - 6w",
      endDate: "2025-03-17",
    },
    assignments: {
      "Q1C2-W1": 1,
      "Q1C2-W2": 1,
      "Q1C2-W3": 1,
      "Q1C2-W5": 1,
    },
  },
  {
    vaultId: "33422",
    team: "Developer Tools",
    theme: "",
    project: "Theme block support in theme check",
    mergedPhase: "nan",
    doneDate: "2025-02-10",
    vaultStatus: "At Risk",
    vaultPhase: "done",
    priority: "P0",
    champion: "Gray Gilmore",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-06" },
    engineering: {
      effort: 8,
      plannedICs: 2,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 4,
      maxWeeks: 5,
      buildWeeks: "4w - 5w",
      endDate: "2025-02-10",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 2,
      "Q1C1-W5": 1,
    },
  },
  {
    vaultId: "41789",
    team: "Developer Tools",
    theme: "",
    project: "Support multiple import maps in Online Store and SFR",
    mergedPhase: "nan",
    doneDate: "2025-02-28",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "P1",
    champion: "Fran Dios",
    editions: "nan",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-27" },
    engineering: {
      effort: 2,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 2,
      maxWeeks: 2,
      buildWeeks: "2w",
      endDate: "2025-02-10",
    },
    assignments: {
      "Q1C2-W2": 1,
    },
  },
  {
    vaultId: "41186",
    team: "Liquid Storefronts Platform",
    theme: "",
    project: "Refactor pages, blogs, and articles out of online store web and into web",
    mergedPhase: "nan",
    doneDate: "2025-02-03",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "P1",
    champion: "Matt Koenig",
    editions: "nan",
    projectedStart: { cycle: "24-Q4C2", date: "2024-11-11" },
    engineering: {
      effort: 9,
      plannedICs: 1,
      certainty: "Known solution",
      overflowWeeks: 1,
      minWeeks: 9,
      maxWeeks: 11,
      buildWeeks: "9w - 12w",
      endDate: "2025-02-03",
    },
    assignments: {
      "Q1C1-W2": 1,
      "Q1C1-W3": 1,
      "Q1C1-W4": 1,
      "Q1C1-W5": 1,
    },
  },
  {
    vaultId: "42116",
    team: "Liquid Storefronts",
    theme: "",
    project: "Online Store + Checkout and Accounts Editor: New Settings UI",
    mergedPhase: "done",
    doneDate: "2025-03-14",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "P0",
    champion: "Nick Lépine",
    editions: "W'24",
    projectedStart: { cycle: "24-Q4C2", date: "2024-11-11" },
    engineering: {
      effort: 7,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 7,
      maxWeeks: 7,
      buildWeeks: "7w",
      endDate: "2024-12-30",
    },
    assignments: {
      "Q1C1-W2": 1,
    },
  },
  {
    vaultId: "42491",
    team: "Liquid Storefronts",
    theme: "",
    project: "Deprecate Monotype fonts",
    mergedPhase: "paused",
    doneDate: "2025-06-06",
    vaultStatus: "At Risk",
    vaultPhase: "paused",
    priority: "P1",
    champion: "Misha Damjanic",
    editions: "nan",
    projectedStart: { cycle: "25-Q1C2", date: "2025-02-10" },
    engineering: {
      effort: 8,
      plannedICs: 1,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 8,
      maxWeeks: 10,
      buildWeeks: "8w - 10w",
      endDate: "2025-04-21",
    },
    assignments: {
      "Q1C2-W2": 1,
    },
  },
  {
    vaultId: "42765",
    team: "Liquid Storefronts",
    theme: "",
    project: "Internal Data Reporting for Shop Onboarding",
    mergedPhase: "done",
    doneDate: "2025-03-26",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "nan",
    champion: "Matt Tetkoskie",
    editions: "nan",
    projectedStart: { cycle: "24-Q4C1", date: "2024-09-30" },
    engineering: {
      effort: 2,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 2,
      maxWeeks: 2,
      buildWeeks: "2w",
      endDate: "2024-10-14",
    },
    assignments: {},
  },
  {
    vaultId: "38212",
    team: "Merchant Workflows",
    theme: "",
    project: "New Online Store Preview Bar",
    mergedPhase: "observe",
    doneDate: "2025-05-16",
    vaultStatus: "On Track",
    vaultPhase: "observe",
    priority: "P0",
    champion: "Nick Lépine",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2024-12-30" },
    engineering: {
      effort: 11,
      plannedICs: 2,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 6,
      maxWeeks: 7,
      buildWeeks: "6w - 7w",
      endDate: "2025-02-17",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 2,
      "Q1C1-W5": 1,
    },
  },
  {
    vaultId: "38213",
    team: "Merchant Workflows",
    theme: "",
    project: "Themes as a compatible responder to the new Market primitive",
    mergedPhase: "release",
    doneDate: "2025-06-01",
    vaultStatus: "On Track",
    vaultPhase: "release",
    priority: "P0",
    champion: "Nick Lépine",
    editions: "S'25",
    projectedStart: { cycle: "24-Q4C1", date: "2024-09-30" },
    engineering: {
      effort: 120,
      plannedICs: 5,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 24,
      maxWeeks: 30,
      buildWeeks: "24w - 30w",
      endDate: "2025-04-28",
    },
    assignments: {
      "Q1C1-W2": 5,
      "Q1C1-W3": 4,
      "Q1C1-W4": 5,
      "Q1C1-W5": 7,
      "Q1C1-W6": 7,
      "Q1C2-W1": 6,
      "Q1C2-W2": 5,
      "Q1C2-W3": 6,
      "Q1C2-W4": 6,
      "Q1C2-W5": 5,
      "Q1C2-W6": 7,
      "Q2C1-W1": 5,
      "Q2C1-W2": 5,
      "Q2C1-W3": 5,
      "Q2C1-W4": 3,
      "Q2C1-W5": 2,
      "Q2C1-W6": 2,
    },
  },
  {
    vaultId: "40977",
    team: "Merchant Workflows",
    theme: "",
    project: "App Extensions Dev Dashboard",
    mergedPhase: "nan",
    doneDate: "",
    vaultStatus: "nan",
    vaultPhase: "nan",
    priority: "nan",
    champion: "Phong Pham",
    editions: "nan",
    projectedStart: { cycle: "nan", date: "" },
    engineering: {
      effort: 0,
      plannedICs: 0,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 0,
      maxWeeks: 0,
      buildWeeks: "",
      endDate: "",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 1,
      "Q1C2-W1": 1,
    },
  },
  {
    vaultId: "44772",
    team: "Theme Customization",
    theme: "",
    project: "AI Theme Block Generation",
    mergedPhase: "build",
    doneDate: "2025-06-20",
    vaultStatus: "On Track",
    vaultPhase: "build",
    priority: "P0",
    champion: "Nick Lépine",
    editions: "S'25",
    projectedStart: { cycle: "nan", date: "" },
    engineering: {
      effort: 0,
      plannedICs: 0,
      certainty: "Fuzzy aim",
      overflowWeeks: 0,
      minWeeks: 0,
      maxWeeks: 0,
      buildWeeks: "",
      endDate: "",
    },
    assignments: {
      "Q1C2-W2": 1,
      "Q1C2-W3": 1,
      "Q1C2-W4": 1,
      "Q1C2-W5": 3,
      "Q1C2-W6": 3,
      "Q2C1-W1": 3,
      "Q2C1-W2": 3,
      "Q2C1-W3": 5,
      "Q2C1-W4": 6,
      "Q2C1-W5": 6,
      "Q2C1-W6": 6,
      "Q2C2-W1": 7,
      "Q2C2-W2": 7,
      "Q2C2-W3": 7,
    },
  },
  {
    vaultId: "44874",
    team: "Theme Customization",
    theme: "",
    project: "block previews",
    mergedPhase: "nan",
    doneDate: "2025-05-20",
    vaultStatus: "On Track",
    vaultPhase: "build",
    priority: "P0",
    champion: "Mia Zbikowski,Philippe Collin",
    editions: "S'25",
    projectedStart: { cycle: "nan", date: "" },
    engineering: {
      effort: 0,
      plannedICs: 0,
      certainty: "Fuzzy solution",
      overflowWeeks: 0,
      minWeeks: 0,
      maxWeeks: 0,
      buildWeeks: "",
      endDate: "",
    },
    assignments: {
      "Q1C2-W1": 1,
      "Q1C2-W2": 1,
      "Q1C2-W3": 3,
      "Q2C1-W1": 2,
      "Q2C1-W2": 3,
      "Q2C1-W3": 3,
      "Q2C1-W4": 3,
      "Q2C1-W5": 3,
      "Q2C1-W6": 3,
      "Q2C2-W1": 3,
    },
  },
  {
    vaultId: "44144",
    team: "Theme Customization",
    theme: "",
    project: "nan",
    mergedPhase: "nan",
    doneDate: "",
    vaultStatus: "On Track",
    vaultPhase: "nan",
    priority: "P0",
    champion: "Irene Nam",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-07" },
    engineering: {
      effort: 40,
      plannedICs: 4,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 10,
      maxWeeks: 13,
      buildWeeks: "10w - 13w",
      endDate: "2025-04-08",
    },
    assignments: {
      "Q1C1-W2": 4,
      "Q1C1-W3": 4,
      "Q1C1-W4": 4,
      "Q1C1-W5": 4,
      "Q1C1-W6": 4,
      "Q1C2-W1": 4,
      "Q1C2-W2": 4,
      "Q1C2-W3": 4,
      "Q1C2-W4": 4,
      "Q1C2-W5": 4,
      "Q1C2-W6": 4,
      "Q2C1-W1": 4,
      "Q2C1-W2": 4,
      "Q2C1-W3": 4,
      "Q2C1-W4": 4,
      "Q2C1-W5": 4,
    },
  },
  {
    vaultId: "44870",
    team: "Theme Customization",
    theme: "",
    project: "Copy and Paste",
    mergedPhase: "observe",
    doneDate: "2025-05-09",
    vaultStatus: "On Track",
    vaultPhase: "release",
    priority: "P0",
    champion: "Mateus Jabour",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-02-17" },
    engineering: {
      effort: 8,
      plannedICs: 2,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 4,
      maxWeeks: 4,
      buildWeeks: "4w",
      endDate: "2025-03-17",
    },
    assignments: {
      "Q1C2-W1": 1,
      "Q1C2-W2": 1,
      "Q1C2-W3": 2,
      "Q1C2-W4": 2,
      "Q1C2-W5": 2,
      "Q1C2-W6": 2,
    },
  },
  {
    vaultId: "43106",
    team: "Theme Customization",
    theme: "",
    project: "Support additional dynamic source attributes",
    mergedPhase: "nan",
    doneDate: "2025-02-13",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "nan",
    champion: "Mbarak Bujra",
    editions: "W'24",
    projectedStart: { cycle: "24-Q4C1", date: "2024-09-30" },
    engineering: {
      effort: 2,
      plannedICs: 1,
      certainty: "Obvious solution",
      overflowWeeks: 0,
      minWeeks: 2,
      maxWeeks: 2,
      buildWeeks: "2w",
      endDate: "2024-10-14",
    },
    assignments: {},
  },
  {
    vaultId: "44140",
    team: "Theme Customization",
    theme: "",
    project: "Conditional Settings for Themes",
    mergedPhase: "observe",
    doneDate: "2025-05-12",
    vaultStatus: "On Track",
    vaultPhase: "release",
    priority: "P0",
    champion: "Albert chu",
    editions: "S'25",
    projectedStart: { cycle: "25-Q1C1", date: "2025-01-07" },
    engineering: {
      effort: 12,
      plannedICs: 2,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 6,
      maxWeeks: 8,
      buildWeeks: "6w - 8w",
      endDate: "2025-03-04",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 1,
      "Q1C1-W5": 2,
      "Q1C1-W6": 2,
      "Q1C2-W1": 2,
      "Q1C2-W2": 1,
      "Q1C2-W3": 1,
    },
  },
  {
    vaultId: "44874",
    team: "Theme Customization",
    theme: "",
    project: "Preset categories",
    mergedPhase: "release",
    doneDate: "2025-05-20",
    vaultStatus: "On Track",
    vaultPhase: "paused",
    priority: "P1",
    champion: "Philippe Collin",
    editions: "S'25",
    projectedStart: { cycle: "25-Q2C2", date: "2025-02-17" },
    engineering: {
      effort: 29,
      plannedICs: 5,
      certainty: "Known solution",
      overflowWeeks: 2,
      minWeeks: 6,
      maxWeeks: 7,
      buildWeeks: "6w - 9w",
      endDate: "2025-04-21",
    },
    assignments: {
      "Q1C2-W2": 2,
      "Q1C2-W3": 3,
      "Q1C2-W4": 3,
      "Q1C2-W6": 1,
      "Q2C1-W1": 2,
    },
  },
  {
    vaultId: "44871",
    team: "Theme Customization",
    theme: "",
    project: "Drag and Drop BED",
    mergedPhase: "build",
    doneDate: "2025-07-31",
    vaultStatus: "On Track",
    vaultPhase: "paused",
    priority: "P1",
    champion: "Irene Nam",
    editions: "S'25",
    projectedStart: { cycle: "25-Q2C2", date: "2025-01-22" },
    engineering: {
      effort: 18,
      plannedICs: 3,
      certainty: "Known solution",
      overflowWeeks: 1,
      minWeeks: 6,
      maxWeeks: 8,
      buildWeeks: "6w - 9w",
      endDate: "2025-03-26",
    },
    assignments: {
      "Q1C2-W6": 3,
    },
  },
  {
    vaultId: "44871",
    team: "Theme Customization",
    theme: "",
    project: "Drag and Drop FED",
    mergedPhase: "build",
    doneDate: "2025-07-31",
    vaultStatus: "On Track",
    vaultPhase: "build",
    priority: "P1",
    champion: "Mateus Jabour",
    editions: "S'25",
    projectedStart: { cycle: "25-Q2C2", date: "2025-03-24" },
    engineering: {
      effort: 12,
      plannedICs: 2,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 6,
      maxWeeks: 8,
      buildWeeks: "6w - 8w",
      endDate: "2025-05-19",
    },
    assignments: {
      "Q2C1-W1": 2,
      "Q2C1-W2": 1,
      "Q2C1-W3": 2,
      "Q2C1-W4": 2,
      "Q2C1-W5": 2,
      "Q2C1-W6": 2,
    },
  },
  {
    vaultId: "33422",
    team: "Theme Customization",
    theme: "",
    project: "Theme Blocks",
    mergedPhase: "observe",
    doneDate: "2025-05-16",
    vaultStatus: "On Track",
    vaultPhase: "observe",
    priority: "nan",
    champion: "Stephanie Chou",
    editions: "W'24",
    projectedStart: { cycle: "24-Q4C2", date: "2024-11-11" },
    engineering: {
      effort: 0,
      plannedICs: 0,
      certainty: "",
      overflowWeeks: 0,
      minWeeks: 0,
      maxWeeks: 0,
      buildWeeks: "",
      endDate: "",
    },
    assignments: {
      "Q1C1-W2": 1,
      "Q1C1-W3": 2,
    },
  },
  {
    vaultId: "44148",
    team: "Theme Customization",
    theme: "",
    project: "Unified Pickers",
    mergedPhase: "stopped",
    doneDate: "2025-03-10",
    vaultStatus: "At Risk",
    vaultPhase: "paused",
    priority: "P1",
    champion: "Philippe Collin",
    editions: "W'25",
    projectedStart: { cycle: "25-Q2C2", date: "2025-06-07" },
    engineering: {
      effort: 18,
      plannedICs: 2,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 9,
      maxWeeks: 11,
      buildWeeks: "9w - 11w",
      endDate: "2025-08-23",
    },
    assignments: {
      "Q1C1-W2": 2,
      "Q1C1-W3": 2,
      "Q1C1-W4": 1,
    },
  },
  {
    vaultId: "41505",
    team: "Theme Customization",
    theme: "",
    project: "Metaobjects work with any theme template via global metaobjects",
    mergedPhase: "done",
    doneDate: "2025-03-07",
    vaultStatus: "On Track",
    vaultPhase: "done",
    priority: "nan",
    champion: "Philippe Collin",
    editions: "W'24",
    projectedStart: { cycle: "24-Q4C2", date: "2024-11-11" },
    engineering: {
      effort: 36,
      plannedICs: 3,
      certainty: "Known solution",
      overflowWeeks: 0,
      minWeeks: 12,
      maxWeeks: 15,
      buildWeeks: "12w - 15w",
      endDate: "2025-02-24",
    },
    assignments: {
      "Q1C1-W2": 1,
      "Q1C1-W3": 1,
      "Q1C1-W4": 1,
    },
  },
  {
    vaultId: "40583",
    team: "Theme Customization",
    theme: "",
    project: "Data sources for Nested Blocks",
    mergedPhase: "done",
    doneDate: "2025-03-14",
    vaultStatus: "At Risk",
    vaultPhase: "done",
    priority: "nan",
    champion: "Feken Baboyan",
    editions: "W'24",
    projectedStart: { cycle: "24-Q4C1", date: "2024-09-30" },
    engineering: {
      effort: 16,
      plannedICs: 2,
      certainty: "Fuzzy solution",
      overflowWeeks: 0,
      minWeeks: 8,
      maxWeeks: 12,
      buildWeeks: "8w - 12w",
      endDate: "2024-12-23",
    },
    assignments: {
      "Q1C1-W2": 1,
    },
  },
];
